name: Main

on:
  push:
    branches:
      - 'main'

jobs:

  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: cd ./app && npm i && tsc && browserify ./index.js -o ../index.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: /
